//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csgo_Command_Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csgo_Command_Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bind mwheelup +jump;bind mwheeldown +jump;bind space +jump
        ///&quot;use weapon_knife;slot1&quot;
        ///bind 1 &quot;slot1; cl_crosshairsize 3&quot;; bind 2 &quot;slot2 ; cl_crosshairsize 3&quot;; bind 3 &quot;slot3 ; cl_crosshairsize 3&quot;; bind 4 &quot;slot8 ; cl_crosshairsize 1000&quot;
        ///&quot;use weapon_knife; use weapon_c4; drop; slot1&quot;
        ///&quot;r_cleardecals&quot;
        ///&quot;toggle cl_righthand 0 1&quot;
        ///&quot;sv_cheats 1; noclip&quot;
        ///alias +jumpthrow &quot;+jump;-attack&quot;; alias &quot;-jumpthrow&quot; &quot;-jump&quot;
        ///alias +netg &quot;net_graph 1;+showscores&quot;;alias -netg &quot;net_graph 0;-showscores&quot;
        ///alias +incvol &quot;increme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Binds {
            get {
                return ResourceManager.GetString("Binds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bind will cause you to jump whenever your mouse wheel is scrolled up on down. This is commonly used by players to make bunny hopping easier, but for others it is simply more convenient than the space bar. Find variations for mouse wheel down or mouse wheel up only on the more information page.
        ///A quickswitch bind will switch to your knife, and then quickly back to your weapon when the binded key is pressed. This bind is commonly used by players who use AWPs, scouts and in some cases deagles to instantl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionofBinds {
            get {
                return ResourceManager.GetString("DescriptionofBinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO
        ///YES
        ///NO
        ///YES
        ///YES
        ///YES
        ///YES
        ///&quot;+jumpthrow&quot;
        ///&quot;+netg&quot;
        ///&quot;+incvol&quot;
        ///YES
        ///&quot;+bombfind&quot;
        ///YES
        ///YES.
        /// </summary>
        internal static string HowToBind {
            get {
                return ResourceManager.GetString("HowToBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHEAT
        ///
        ///CHEAT
        ///
        ///
        ///
        ///
        ///
        ///
        ///CHEAT
        ///CHEAT
        ///
        ///
        ///
        ///
        ///CHEAT
        ///
        ///CHEAT
        ///
        ///CHEAT
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///CHEAT
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///CHEAT
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///CHEAT
        ///
        ///CHEAT
        ///CHEAT
        ///CHEAT
        ///
        ///
        ///
        ///CHEAT
        ///CHEAT
        ///
        ///
        ///CHEAT
        ///CHEAT
        ///
        ///
        ///
        ///
        ///
        ///CHEAT
        ///
        ///
        ///
        ///CHEAT
        ///CHEAT
        ///
        ///
        ///
        ///
        ///CHEAT
        ///CHEAT
        ///CHEAT
        ///CHEAT
        ///
        ///CHEAT
        ///CHEAT
        ///CHEAT
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///CHEAT
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListofCheats {
            get {
                return ResourceManager.GetString("ListofCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @panorama_debug_overlay_opacity
        ///@panorama_force_sort_child_ops
        ///_autosave
        ///_autosavedangerous
        ///_bugreporter_restart
        ///_record
        ///_resetgamestats
        ///_restart
        ///achievement_debug
        ///achievement_disable
        ///addip
        ///adsp_debug
        ///adsp_reset_nodes
        ///ai_clear_bad_links
        ///ai_debug_los
        ///ai_debug_node_connect
        ///ai_debug_shoot_positions
        ///ai_disable
        ///ai_drawbattlelines
        ///ai_drop_hint
        ///ai_dump_hints
        ///ai_hull
        ///ai_next_hull
        ///ai_nodes
        ///ai_report_task_timings_on_limit
        ///ai_resume
        ///ai_set_move_height_epsilon
        ///ai_setenabled
        ///ai_show_connect
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListofCommands {
            get {
                return ResourceManager.GetString("ListofCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Autosave
        ///Autosavedangerous
        ///Restarts bug reporter .dll
        ///Record a demo incrementally.
        ///Erases current game stats and writes out a blank stats file
        ///Shutdown and restart the engine.
        ///Turn on achievement debug msgs.
        ///Turn off achievements.
        ///Add an ip address to the ban list.
        ///
        ///
        ///Clears bits set on nav links indicating link is unusable 
        ///Npc line-of-sight debug mode. If 1, solid entities that block npc loc will be highlighted with white bounding boxes. If 2, it&apos;l
        ///Debug the attempted connection between tw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListofDescriptions {
            get {
                return ResourceManager.GetString("ListofDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///0
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///0
        ///0
        ///cmd
        ///0
        ///cmd
        ///cmd
        ///0
        ///cmd
        ///0
        ///cmd
        ///0
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///0
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///0
        ///1
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///30
        ///52
        ///12
        ///26
        ///24
        ///100
        ///35
        ///200
        ///90
        ///40
        ///100
        ///90
        ///120
        ///32
        ///3
        ///3
        ///1
        ///1
        ///3
        ///3
        ///4
        ///0
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///cmd
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///5
        ///-2
        ///0
        ///0
        ///1400
        ///0
        ///0
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListofValues {
            get {
                return ResourceManager.GetString("ListofValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mousewheel Jump Bind
        ///Quickswitch Bind
        ///Nade Lineup Crosshair Bind
        ///Drop Bomb Bind
        ///Clear Decals Bind
        ///Switch Hands Bind
        ///Noclip Bind
        ///Jump Throw Bind
        ///Net_graph Scoreboard Bind
        ///Increase Volume When Walking Bind
        ///Zoom Radar Bind
        ///Easy way to find a bomb
        ///Runthrow
        ///Change crosshair size
        ///.
        /// </summary>
        internal static string NameofBinds {
            get {
                return ResourceManager.GetString("NameofBinds", resourceCulture);
            }
        }
    }
}
